import { getDatabase } from './database'

// ---------------------------------------------------------------------------
// Expenses — every dirham the shop spends that is not stock.
//
// Migration 44 gave the table the columns a ledger actually needs: a category,
// the shop it belongs to, the date it was INCURRED (as opposed to typed in),
// and a provenance pair. That last one is what lets payroll post itself here
// without the risk of double-charging: `source_type`/`source_ref` carry a unique
// index, so a generated row can be re-posted idempotently while hand-entered
// rows (source_type NULL) are untouched.
//
// `spent_at` vs `created_at`: a September electricity bill entered in October is
// a September cost. Every filter here reads spent_at and falls back to
// created_at for rows written before the column existed.
// ---------------------------------------------------------------------------

export interface Expense {
    id: number
    name: string
    amount: number
    category: string | null
    store_id: number | null
    spent_at: string | null
    source_type: string | null
    source_ref: string | null
    created_by: number | null
    created_at: string
    store_name?: string | null
}

export interface ExpenseFilters {
    from?: string
    to?: string
    storeId?: number | null
    category?: string | null
}

/** The categories the UI offers. Free text is still accepted — this is a
 *  starting vocabulary, not a constraint, because a shop will always have a
 *  cost nobody anticipated. 'salaires' is generated by payroll. */
export const EXPENSE_CATEGORIES = [
    'loyer', 'salaires', 'electricite', 'eau', 'internet', 'transport',
    'marketing', 'entretien', 'fournitures', 'impots', 'divers',
] as const

const DATE_COL = 'COALESCE(spent_at, created_at)'

function scope(f: ExpenseFilters) {
    const where: string[] = []
    const params: any[] = []
    if (f.from) { where.push(`${DATE_COL} >= ?`); params.push(f.from) }
    if (f.to) { where.push(`${DATE_COL} <= ?`); params.push(f.to) }
    if (f.storeId != null) { where.push('e.store_id = ?'); params.push(f.storeId) }
    if (f.category) { where.push('e.category = ?'); params.push(f.category) }
    return { clause: where.length ? `WHERE ${where.join(' AND ')}` : '', params }
}

export const ExpenseService = {
    create(
        name: string,
        amount: number,
        userId?: number,
        opts: { category?: string; storeId?: number | null; spentAt?: string } = {},
    ) {
        const db = getDatabase()
        const result = db.prepare(`
            INSERT INTO expenses (name, amount, created_by, category, store_id, spent_at)
            VALUES (?, ?, ?, ?, ?, ?)
        `).run(
            name,
            Number(amount) || 0,
            userId || null,
            opts.category || 'divers',
            opts.storeId ?? null,
            opts.spentAt || new Date().toISOString().slice(0, 19).replace('T', ' '),
        )
        return { id: result.lastInsertRowid as number }
    },

    getAll(filters: ExpenseFilters = {}): Expense[] {
        const db = getDatabase()
        const { clause, params } = scope(filters)
        return db.prepare(`
            SELECT e.*, s.name AS store_name
            FROM expenses e
            LEFT JOIN stores s ON s.id = e.store_id
            ${clause}
            ORDER BY ${DATE_COL} DESC, e.id DESC
        `).all(...params) as Expense[]
    },

    /** Totals per category for a window — the breakdown a P&L needs. */
    byCategory(filters: ExpenseFilters = {}) {
        const db = getDatabase()
        const { clause, params } = scope(filters)
        return db.prepare(`
            SELECT COALESCE(e.category, 'divers') AS category,
                   COALESCE(SUM(e.amount), 0) AS total,
                   COUNT(*) AS lines
            FROM expenses e
            ${clause}
            GROUP BY COALESCE(e.category, 'divers')
            ORDER BY total DESC
        `).all(...params) as { category: string; total: number; lines: number }[]
    },

    /** One number for a window. Used by anything that subtracts expenses. */
    total(filters: ExpenseFilters = {}): number {
        const db = getDatabase()
        const { clause, params } = scope(filters)
        const row = db.prepare(`
            SELECT COALESCE(SUM(e.amount), 0) AS total FROM expenses e ${clause}
        `).get(...params) as { total: number }
        return row.total
    },

    getTotals(storeId?: number | null) {
        const db = getDatabase()
        const now = new Date()

        const getTotal = (days: number) => {
            const date = new Date(now)
            date.setDate(date.getDate() - days)
            const dateStr = date.toISOString().split('T')[0]
            const params: any[] = [dateStr]
            let storeClause = ''
            if (storeId != null) { storeClause = 'AND store_id = ?'; params.push(storeId) }
            const result = db.prepare(`
                SELECT COALESCE(SUM(amount), 0) as total FROM expenses
                WHERE date(${DATE_COL}) >= ? ${storeClause}
            `).get(...params) as { total: number }
            return result.total
        }

        return {
            total7D: getTotal(7),
            total1M: getTotal(30),
            total6M: getTotal(180),
            total1Y: getTotal(365),
        }
    },

    /** Hand-entered rows only. A generated one (payroll) must be corrected at
     *  its source and re-posted, or the ledger and the payslips disagree. */
    delete(id: number) {
        const db = getDatabase()
        const row = db.prepare('SELECT source_type FROM expenses WHERE id = ?').get(id) as
            { source_type: string | null } | undefined
        if (row?.source_type) {
            return {
                success: false,
                error: 'Cette dépense est générée par la paie. Corrigez la fiche de paie puis relancez la comptabilisation.',
            }
        }
        db.prepare('DELETE FROM expenses WHERE id = ?').run(id)
        return { success: true }
    },
}
